name: Terraform AWS Resources

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # Replace with your desired AWS region
      DIR_TO_ITERATE: ./a_test_cms/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
        for dir in $DIR_TO_ITERATE; do
          for d in "$dir"; do
            (cd "$d" && terraform init)
          done  
        done

    - name: Terraform Plan
      run: |
        for dir in $DIR_TO_ITERATE; do
          for d in "$dir"; do
            (cd "$d" && terraform plan -input=false -out=tfplan)
          done  
        done

    - name: Terraform Apply
      run: |
        for dir in $DIR_TO_ITERATE; do
          for d in "$dir"; do
            (cd "$d" && terraform apply -auto-approve tfplan)
          done  
        done



