name: Terraform AWS Resources

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2  # Replace with your desired AWS region
      DIR_TO_ITERATE: ./a_test_cms/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
         cd a_test_cms\terraform-aws-cognito-user-pool-master\example
         terraform init
     

    - name: Terraform Plan
      run: |
        cd a_test_cms\terraform-aws-cognito-user-pool-master\example
        terraform fmt
     

    - name: Terraform Apply
      run:  terraform plan
      working-directory: ./a_test_cms/terraform-aws-cognito-user-pool-master/example  
        


